sudo: required
services: 
  - docker

before_install:
  - docker build -t parthghetia/docker-training -f Dockerfile.dev .

script:
  - docker run -e CI=true parthghetia/docker-training npm run test


